# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
flashlight_list = [
  [ "61", "tk" ,100 , 100 , "The Fenix TK61 is scaled for extended operation in challenging conditions with max 1000 lumens output. Utilizing a single CREE XM-L2 U2 LED, the TK61 employs dual on-body switches for rapid shifting between four brightness levels and two flashing modes with runtime well beyond 4hrs on Turbo. The824mthrow reaches deep while an extended runtime kit stays the course whether the TK61 is handheld, shoulder-strap carried or vehicle-mounted","·Uses Cree XM-L2 LED with a lifespan of 50000 hour·Uses four 18650 rechargeable Li-ion batteries or eight 3V CR123A Lithium batteries·216mm (Length)﹡52.5mm (Diameter)﹡96mm(Head)·600-gram weight (excluding batteries)·Digitally regulated output - maintains constant brightness·Reverse polarity protection, to protect from improper battery installation·Dual switch system in the front, simple and fast operation·Made of durable aircraft-grade aluminum·Premium Type III hard-anodized anti-abrasive finish·Toughened ultra-clear glass lens with anti-reflective coating","lala","http://fenixlight.com/Uploads/photo/210201483232PM55645.jpg"],
  ["76" , "tk" , 200 , 200 , "The Fenix TK76 Flashlight utilizes three separate LEDs to offer a broad range of illumination options and power display function. Output up to 2800 lumens creates intense area lighting combined with long reach. Ideal for group leaders needing high output and multiple beam patterns, the Fenix TK76 is a powerful addition to a team’s onsite lighting tools with instant turbo, strobe and SOS" , "·Uses two Cree XM-L2 (U2) LEDs and one Cree XM-L2 T6 neutral white LED with a lifespan of 50000 hours·222mm (Length) x 55mm (Diameter) x 100mm (Head length) x77mm (Head Width)·800-gram weight (excluding batteries)·Digitally regulated output - maintains constant brightness·Reverse polarity protection guards against improper battery installation·Intelligent thermal control  to protect the flashlight against over-heat·Tri-color displays indicate the running level and the remaining power with low-power warning·Anti-roll and slip-resistant  body design·Independently–controlled lighting heads permit easy and fast operation·Instant Turbo activation for immediate illumination ·Made of durable aircraft-grade aluminum·Premium Type III hard-anodized anti-abrasive finish·Toughened ultra-clear glass lens with anti-reflective coating and quality PC lens" , "jaja" , "http://fenixlight.com/Uploads/photo/128201373650PM67917.jpg"],
  ["50" , "e" , 300 , 300 ,"Slim, super bright and easy to use, E50 is truly a powerhouse in your hand. Powered by two 18650 batteries or four CR123Abatteries, E50 delivers a 780-lumen neutral white beam and runs for 80 hours in low mode. With the adjustable battery tube and four brightness levels, you can easily customize the size, output and runtime of the flashlight to best suit your adventure","· Cree XM-L (T6) neutral white LED with a lifespan of 50,000 hours· Use two 18650 batteries or four CR123Abatteries· 207mm(Length) x40mm(Diameter)· 146.6-gram weight (excluding batteries)· Digitally regulated output - maintains constant brightness· Reverse polarity protection guards against improper battery installation· All-function switch on the head, simple and convenient operation · Made of durable aircraft-grade aluminum· Premium Type III hard-anodized anti-abrasive finish· Toughened ultra-clear glass lens with anti-reflective coating","jaja","http://fenixlight.com/Uploads/photo/201312616243825212.jpg"],
  ["25" , "e" , 300 , 300 ,"Fenix E25 is a compact, versatile outdoor flashlight. The All-function switch on the head gives you total control of the light. Activating the light or choosing an ideal output is simple and intuitive. Powered by 2 readily available AA batteries, E25 delivers a max 187-lumen output and 26 hours runtime on low mode. Featuring constant brightness technology and waterproof to IPX-8 standard, E25 is another high-performance addition to the growing Fenix product line.","· Cree XP-E  LED with a lifespan of 50,000 hours· Uses two AA batteries· 146mm(Length) x24mm(Diameter)· 75-gram weight (excluding batteries )· Digitally regulated output - maintains constant brightness· Reverse polarity protection guards against improper battery installation· Slip-resistant body design· All-function switch, simple and convenient operation· Capable of standing up securely on a flat surface to serve as a candle· Made of durable aircraft-grade aluminum· Premium Type III hard-anodized anti-abrasive finish· Toughened ultra-clear glass lens with anti-reflective coating","jaja","http://fenixlight.com/Uploads/photo/201312616261049730.jpg"]
]

flashlight_list.each do |model, serie , price, lumens,  description , features , specifications , image|
  Flashlight.create( model:model, serie:serie , price:price, lumens:lumens,  description:description , features:features , specifications:specifications , remote_image_url:image)
end